### PR TITLE
Major update to UxPlay (includes setting resolution, network ports, and much more)

### PR DESCRIPTION
**Pull request by fduncanh**
I don't know if antimof is still active on this site, but this pull request has both new features and fixes, based on requests both here and at RPiPlay.   Much  was just achieved by making hard-coded choices buried in the code accessible for changing., by an API enhancement  FD-/RPiPlay#257 .  Inspiration came from PR's and  Issues discussed here and at https://github.com/FD-/RPiPlay.

1.   new options -s wxh for setting display resolution.  
2. -p or -p n for setting network ports when there is a firewall.   
3.   an optional ZOOMFIX so the display window is visible for screen-sharing on Zoom, etc.
4.  -m to use random MAC address (allows two instances of uxplay on the same computer)
5.  The AirPlay server now terminates correctly and relaunches  when its display window is closed.    The Avahi-compat startup nag message is gone.
6. All updates of the AirPlay RAOP  ibrary from the RPiPlay project are  ported to  this new UxPlay.

and more .(see the README on the https://github.com/FDH2/UxPlay.git

2021-08-10 extra change: also added settings  -fps for setting max streaming rate from AirPlay client

### CODE REVIEW

**Comment by D3SOX** [comment]
Thanks for your work! Is #31 included? If so I'd use your branch for my AUR package. Otherwise I'll just patch it before building (If it works without conflicts)

**Comment by D3SOX** [comment]
Latest version doesn't build for me
```
[ 84%] Linking C static library libairplay.a
[ 84%] Built target airplay
[ 87%] Building C object renderers/CMakeFiles/renderers.dir/video_renderer_gstreamer.c.o
[ 90%] Building C object renderers/CMakeFiles/renderers.dir/audio_renderer_gstreamer.c.o
[ 93%] Linking C static library librenderers.a
[ 93%] Built target renderers
[ 96%] Building CXX object CMakeFiles/uxplay.dir/uxplay.cpp.o
/home/nico/.cache/yay/uxplay-git/src/UxPlay/uxplay.cpp: In function ‘int start_server(std::vector<char>, std::string, short unsigned int*, short unsigned int*, short unsigned int*, videoflip_t*, bool, bool, std::string)’:
/home/nico/.cache/yay/uxplay-git/src/UxPlay/uxplay.cpp:456:46: error: too many arguments to function ‘video_renderer_t* video_renderer_init(logger_t*, const char*, videoflip_t*)’
  456 |     if ((video_renderer = video_renderer_init(render_logger, name.c_str(), videoflip, videosink.c_str())) == NULL) {
      |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nico/.cache/yay/uxplay-git/src/UxPlay/uxplay.cpp:33:
/home/nico/.cache/yay/uxplay-git/src/UxPlay/renderers/video_renderer.h:47:19: note: declared here
   47 | video_renderer_t *video_renderer_init (logger_t *logger, const char *server_name, videoflip_t videoflip[2]);
      |                   ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/uxplay.dir/build.make:76: CMakeFiles/uxplay.dir/uxplay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: CMakeFiles/uxplay.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: uxplay-git
```

**Comment by rbribeiro** [comment]
@fduncanh thank you for all your changes! Now, I worried that @antimof  is not keeping this repo active anymore. In that case, do you think we should use your repo instead?

**Comment by fduncanh** [comment]
@rbribeiro 

_ @fduncanh thank you for all your changes! Now, I worried that @antimof is not keeping this repo active anymore. In that case, do you think we should use your repo instead?_

Yes you should probably publicize http://github.com/FDH2/UxPlay as the place to get updated UxPlay on your blog(s)!

**Comment by fduncanh** [comment]
@D3SOX  Please see https://github.com/FDH2/Uxplay#135

**Pull request merged**
